apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: enterprise-platform
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/abhinav211/enterprise-microservices.git
    targetRevision: main
    path: enterprise-platform

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
    - CreateNamespace=true
