employee:
  replicaCount: 2

  image:
    repository: ghcr.io/abhinav211/employee-service
    tag: 5613b1268b5fa12864764cba73821e8b3965fd1a
auth:
  replicaCount: 2
  image: auth-service:v1

gateway:
  replicaCount: 2
  image: api-gateway:v2

postgres:
  image: postgres:15

redis:
  image: redis:7

ingress:
  host: enterprise.local
