employee:
  replicaCount: 2

  image:
    repository: ghcr.io/abhinav211/employee-service
    tag: 6d8b9a8e34b8db6fd099adcd111fd6ac759edbbf
auth:
  replicaCount: 2
  image: auth-service:v1

gateway:
  replicaCount: 2
  image: api-gateway:v2

postgres:
  image: postgres:15

redis:
  image: redis:7

ingress:
  host: enterprise.local
